list    p = 16f887
include <p16f887.inc>
	
__CONFIG _CONFIG1, _FOSC_INTRC_NOCLKOUT & _WDTE_OFF & _MCLRE_ON
	
W_TEMP	    EQU	    0x20	
STATUS_TEMP EQU	    0x21
FSR_TEMP    EQU	    0x22
CONDICION   EQU	    0x23
CANTLED     EQU	    0x24
RESULTADO   EQU	    0x25
	    
org	0x00
goto	SETEO
	
org	0x4
goto	INTERRUPCION
	
org	0x5
SETEO   
	BSF	    STATUS, RP1
	BSF	    STATUS, RP0		; Banco 11:3
	CLRF	    ANSELH		; Se setea puerto B como digital
	
	
 
PROGRAMA
	BTFSS	    CONDICION
	GOTO	    $-1
	
ACTLEDS
	CLRF	    CONDICION
	CLRF	    CANTLED
	
	MOVLW	    D'28'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
	MOVLW	    D'56'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
	MOVLW	    D'84'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    LED,F
	
	MOVLW	    D'112'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
	MOVLW	    D'140'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
	MOVLW	    D'168'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
	MOVLW	    D'196'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
	MOVLW	    D'224'
	SUBWF	    RESULTADO,W
	BTFSS	    STATUS,C
	GOTO	    MOSTRARLED
	INCF	    CANTLED,F
	
MOSTRARLED
	MOVF	    CANTLED,F
	CALL	    TABLA
	MOVWF	    PORTA
	GOTO	    PROGRAMA
	
TABLA
	ADDWF	    PCL,F		; suma a PC el valor del dígito
	RETLW	    B'00000000'
	RETLW	    B'00000001'
	RETLW	    B'00000011'
	RETLW	    B'00000111'
	RETLW	    B'00001111'
	RETLW	    B'00011111'
	RETLW	    B'00111111'
	RETLW	    B'01111111'
	RETLW	    B'11111111'
	
INTERRUPCION
	MOVWF	    W_TEMP		; MOVWF no modifica STATUS. GUARDO CONTEXTO
	SWAPF	    STATUS, W		; SWAPF para mover f a W sin modificar STATUS
	MOVWF	    STATUS_TEMP		; Se guarda contexto: STATUS
	
	BTFSC	    INTCON,T0IF		; Interrumpió TIMER0?
	CALL	    ISTIMER		; Si T0IF está en 1 fue TIMER0 y llamo a ISTIMER
	
	SWAPF	    STATUS_TEMP, W	; Se recupera el contexto
	MOVWF	    STATUS
	SWAPF	    W_TEMP, F
	SWAPF	    W_TEMP, W
	RETFIE